language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y pkg-config libtool autopoint gettext zlib1g-dev libbz2-dev liblzma-dev libselinux1-dev libncursesw5-dev perl libio-string-perl
script:
  - autoreconf -f -i && ./configure --enable-coverage && make check
after_success:
  - bash <(curl -s https://codecov.io/bash)
