language: c
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
  - os: osx
compiler:
  - gcc
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y pkg-config libtool autopoint gettext zlib1g-dev libbz2-dev liblzma-dev libselinux1-dev libncursesw5-dev perl libio-string-perl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gettext libtool xz gnu-tar perl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cpanm IO::String || true; fi
script:
  - PATH=/usr/local/opt/gettext/bin:/usr/local/opt/libtool/bin:$PATH autoreconf -f -i && ./configure && make check
after_success:
  - bash <(curl -s https://codecov.io/bash)
