language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t dpkg/debian:stretch .travis/
script:
  - docker run -v `pwd`:/build dpkg/debian:stretch
    sh -c "
      autoreconf -f -i &&
      ./configure --enable-coverage &&
      make -j4 check
    "
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker run
    -e TRAVIS -e TRAVIS_COMMIT -e TRAVIS_BRANCH -e TRAVIS_JOB_NUMBER
    -e TRAVIS_JOB_ID -e TRAVIS_PULL_REQUEST -e TRAVIS_REPO_SLUG
    -v `pwd`:/build dpkg/debian:stretch
    sh -c "
      cd scripts &&
      /usr/bin/cover -ignore_re '^t/.*\.t' -report codecov
    "
